"""
Recommendation-related ORM models: RiskProfile, RecommendationLog.

These store the user's risk preferences and generated fund recommendations.
"""

from datetime import datetime
from decimal import Decimal
from typing import Any

from sqlalchemy import (
    JSON,
    BigInteger,
    DateTime,
    Numeric,
    String,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class RiskProfile(Base):
    """User's risk tolerance and investment preferences."""

    __tablename__ = "risk_profiles"

    id: Mapped[int] = mapped_column(
        BigInteger, primary_key=True, autoincrement=True
    )
    risk_tolerance: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        comment="Risk tolerance level (e.g. low, medium, high)",
    )
    investment_horizon: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        comment="Investment horizon (e.g. short, medium, long)",
    )
    return_expectation: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        comment="Return expectation (e.g. conservative, moderate, aggressive)",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        comment="Last update timestamp",
    )
    user_id: Mapped[int | None] = mapped_column(
        BigInteger, default=None, nullable=True, comment="Owner user ID"
    )


class RecommendationLog(Base):
    """Log of fund recommendations generated by the system."""

    __tablename__ = "recommendation_logs"

    id: Mapped[int] = mapped_column(
        BigInteger, primary_key=True, autoincrement=True
    )
    fund_code: Mapped[str] = mapped_column(
        String(10), nullable=False, comment="Recommended fund code"
    )
    score: Mapped[Decimal | None] = mapped_column(
        Numeric(10, 2), default=None, comment="Recommendation score"
    )
    strategy: Mapped[str] = mapped_column(
        String(30), nullable=False, comment="Strategy used for recommendation"
    )
    reasons: Mapped[dict[str, Any] | None] = mapped_column(
        JSON, default=None, comment="JSON object describing recommendation reasons"
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        comment="Recommendation generation timestamp",
    )
    user_id: Mapped[int | None] = mapped_column(
        BigInteger, default=None, nullable=True, comment="Owner user ID"
    )
